# Introduction

During our daily life, we move through our environment without constantly thinking about it. Passing from one room into another might be one of the most insignificant actions we do day by day, but the simple act of walking through a door might influence the cognitive processing of whatever we are thinking about - even if the spatial structure of our environment is completely irrelevant to us at that time.

That our cognitive processes are influenced by the environment that we are currently in, is no surprise. In particular, while we are working on a memory task, the environment is encoded along with what we are trying to remember, even if there is no causal or semantic relationship. @Godden_1975 showed in a now well-known experiment that word lists are better remembered if the environmental context is the same while learning and during recall - in particular, divers could recall word lists learned under water better if they were under water, and their performance decreased if they had to recall that list on dry land. This concept is also known as the encoding specificity phenomenon [@Thomson_1970].

More recently, there are several studies that examine working memory performance while people move from one room to another. While this is not at all such a significant context change as diving under water, there is a remarkably consistent effect coined the "doorway effect": When passing from one room to another, memory performance declines [@Radvansky_2006]. 

However, even though both phenomena appear to be variants of the same encoding specificity, or context-dependent memory phenomenon, a closer inspection of the "doorway effect" leads to a different conclusion, as reinstating the original encoding context after walking through a doorway does not improve memory performance again [@Radvansky_2011], in contrast to the findings of @Godden_1975.

The present study aimed to examine the "doorway effect" by trying to replicate it using a different memory task, and additionally looking at the influence that context changes have on this effect.

## The "doorway effect" and event cognition

The "doorway effect" or location updating effect is currently mainly explored from an event cognition perspective - whatever happens in one room constitutes an event, and passing through a doorway means passing an event boundary.

Usually, to demonstrate that walking through doorways causes forgetting, participants are confronted with a very simple task: They are instructed to pick up an object, move through a door into another room and put the object down. Then they pick up the next object and repeat this process. However, shortly after entering the second room, a memory probe appears and participants have to respond whether the memory probe is the object they are currently carrying, the object they just put down, or a new, different object. Remarkably, memory performance as measured by response time and response correctness declines after walking through the door as compared to simply walking through a large room without a doorway - and this happens in a more pronounced way for the "associated", currently carried object [@Radvansky_2006]. This finding is impressive for several reasons: The actual memory load is very low (only the two most recently seen objects are relevant). Additionally, the spatial structure of the room and the fact that participants walk through a door or not is completely irrelevant for the memory task. Lastly, this effect has repeatedly been demonstrated by having participants experience that environment through a non-immersive virtual reality - this means that they control their movement via keyboard or controllers, and they view the environment and their interaction with the objects only on a computer screen.

@Radvansky_2011 demonstrated that this forgetting after walking through a doorway cannot be reversed by simply going back to the original room and thus reinstating the original context, which lead the authors to reject a context-dependent memory account of the doorway phenomenon. Rather, they argue for an event-cognition based account.

In particular in this view, each room and everything that happens in it might be classified as a single event by the brain. For example, when putting a red ball onto the table in room A and picking up a blue cube, both of these objects are now connected to the mental "event model" of room A. When entering room B through a doorway, a new event model needs to be created: This new model encompasses room B and the blue cube that is currently carried - since it now also is in this second room. Importantly, if now a recognition probe for the blue cube is presented, there is an interference happening: Both, room A and room B contain the probed-for object and thus both event models are activated. The resulting interference is assumed to be the reason why memory performance is decreased as compared to the "dissociated" red ball; if the red ball would be the memory probe, then only the event model for room A would have to be activated, with no further interference. If the doorway is removed, room A and room B are perceived as one big, combined room and thus only a single event model needs to be created.

Importantly, this account of event cognition also assumes that there is always only one current, activated event model, which usually contains the immediate and relevant surroundings - for example, the room that one is currently in. When walking through a doorway, this currently active event model switches and the object currently carried is immediately integrated into the newly activated model [@Radvansky_2012].

It is important to note that using this theoretical framework, it is easy to explain why returning to the original room after walking through a doorway does not counteract the forgetting: The carried object still is present in two different event models. The "Event Horizon Model" is a theory based on five principles [@Radvansky_2012] that is used in previous research to explain this surprisingly consistent doorway phenomenon.

With this background, doorways are often assumed to be event boundaries that separate event models, and experimental variations have repeatedly shown evidence in favour of this explanation. There has been a multitude of studies examining the "doorway effect" from different perspectives [@Radvansky_2006; @Radvansky_2010; @Radvansky_2011; @Lawrence_2014; @Pettijohn_2015; @Pettijohn_2016; @Pettijohn_2018a; @Seel_2018; @Logie_2021; @McFadyen_2021; @Watson_2021; @Wang_2023], and a few of these are especially noteworthy in the context of the present study.

Most of those studies describe the experimental task as being "virtual environments" that participants walk through and where they pass through doorways. However, these virtual environments are usually depicted only on a simple computer monitor. Participants control their movement by pressing keys or by using a controller, and even the distinction between the "associated" and "dissociated" object might be questioned, since participants do not actually "carry" the object with them, but have to imagine that they do, aided by the visual representation on the screen.

There are a few exceptions that are interesting: @Lawrence_2014 had participants memorize a real environment by having them physically walk through an actual room constellation - the argument being that participants do not physically have to pass through a doorway, since imagining oneself doing so would have the same effect on cognitive processes. In fact, this study could demonstrate the presence of a "doorway effect". This is evidence in favour of the Event Horizon Model, since that model does not depend on the actual physical or even visual experience of passing through an event boundary, but rather is based on the mental structuring that happens.

Similarly, @Pettijohn_2018a had one participant execute a standard version of the doorway experiment, while a second participant passively watched. Both participants were probed for memory, and both participants did exhibit a location updating effect, albeit smaller for the passive participant. Again, this provides evidence that merely the mental classification of something being an event boundary, regardless of actual personal experience, influences working memory performance.

However, while the "doorway effect" has been found in real [@Radvansky_2011], virtual or imagined environments, @McFadyen_2021 could not replicate it in highly immersive virtual or even real environments. Only if participants had a second distractor task increasing the memory load, the authors found a worse memory performance after walking through doorways. This shows that while the effect seems to be easily replicable, there are conditions under which it seems to be harder. The goal of the present study is to try and replicate a doorway effect using a highly immersive virtual environment.

## The "doorway effect" and context

As mentioned above, @Radvansky_2011 provided evidence suggesting that the doorway phenomenon is not barely an effect of context-dependent memory. In their study, they had participants return to the original room where the objects to be remembered were first encoded. Encoding specificity would predict that memory performance would increase again in that case. However, no such effect was found. Notably, this "return" condition implied that participants had to cross the same doorway - or event boundary - twice, and according to the Event Horizon Model, there would still only be two event models activated (first room A, then room B, then room A again). For comparison, they thus also added a "double shift" condition in which participants had to pass through two rooms, resulting in again two event boundaries, but this time three event models (room A, room B and room C). The result was that returning to the original room did not improve memory performance, and there was a large number of errors in the double shift condition. The authors conclude that for the "doorway effect", it is not the number of event boundaries or doorways that matters, but instead the number of generated event models.

It has to be noted though, that for this study and a majority of the replications, the room context is usually only defined by simple wall colours or at most patterns, and possibly a change in the visual appearance of the floor. While this might visually appear very different, one could question whether this is indeed enough of a difference to be conceptually processed as being different contexts. There are, as previously mentioned, studies that successfully replicate the doorway phenomenon using a real environment [@Lawrence_2014; @Radvansky_2011], but at the same time, this is not always the case [@McFadyen_2021].

Thus, a further goal of the present study is to increase the experience of the two rooms in the task being of a different context. In particular, a highly immersive virtual reality environment is used along with rooms that are visually and semantically different, as indicated by a variety of decorative objects placed in those rooms.

## The present study

While so many replications of the "doorway effect" exist, it is surprising that they almost exclusively use the same task of participants "carrying" one object and putting another one down. This task provides an obvious distinction between an "associated" object being present in two different event models and a "dissociated" object being present in only one. However, focusing on this one task calls into question the robustness and generalizability of the effect, as is evident by the unsuccessful replication by @McFadyen_2021. If indeed having items in working memory connected to two different event models reduces their accessibility, this effect should also be found when using a different task that focuses less on the distinction between "associated" and "dissociated" objects.

The present study used a spatial object layout memory task adapted from @Buelthoff_2000. Participants viewed a layout of objects in one room, then walked into another room and tried to detect whether there was a change in the layout. Importantly, while there is no single "associated" object, the memory of the object layout is connected to both the first room (where it is encoded and memorized) as well as in the second room (where the change detection task happens). This means that for this task, the memory for the object layout should in theory be present in two different event models. It follows that if participants walk through a doorway when they switch rooms (and switch event models), they should show a worse memory performance than if there is no doorway and the two rooms seem to be only one - and thus exist in one single event model.

In order to increase the perception of the rooms being either two separate events or one big event, an additional manipulation of room context was added. If participants walk through a door and the semantic and visual context of the room changes, then this should constitute a very prominent event boundary and thus make separating the event models easier. In contrast, if participants walk from one room to another, but there is neither a doorway nor a change in context, then this should lead participants to use only a single event model, and thus exhibiting comparatively higher memory performance.

To examine participants' performance in this task, an immersive virtual reality environment was used. This allows for a more realistic and ecologically valid approach to examining the doorway phenomenon as compared to presenting the task on a computer screen, which is also aided by the use of stimuli that are not abstract, randomly coloured forms (as has usually been used in previous studies), but objects with everyday names or use cases.