# Discussion

This study aimed to explore the "doorway effect" or location updating effect using an immersive virtual reality environment and a memory task that has previously not been used for studying this phenomenon.

The location updating effect is a disruption in cognitive processing, usually examined by having participants move from one location to another while working on a memory task. Previous research has consistently shown that memory performance is worse after passing through a doorway into the new location [@Radvansky_2006; @Radvansky_2011; @Pettijohn_2016a]. Importantly, this effect can usually be observed even if the memory load for the participants only consists of two objects: one associated, "carried" object and one dissociated, "put-down" object - with a worse memory performance for both objects, but a larger effect on the "associated" object. In order to more closely examine this phenomenon, the present study used a more complex object layout memory task, in which participants had to decide if a spatial arrangement of objects that they viewed in two rooms had changed.

This study could not provide convincing evidence for a location updating effect using this new memory task. Only when analysing the hit rate instead of overall performance, a small effect could be found that indicated reduced memory for the object layout after passing through a doorway. Notably, this effect was slightly more pronounced for the lowest performing participants, indicating that under higher working memory load, a more easily observable location updating effect can be expected, in line with the work by @McFadyen_2021.

## Response times and response correctness are unaffected by doorway and context

For the response times, no effect could be found. This is different in comparison to previous studies examining the "doorway effect" [e.g., @Radvansky_2010], where usually for the doorway condition, slower responses were given. However, the present study used a highly immersive way of participants interacting with the response buttons - instead of pressing a button on the controller, they had to physically move their whole arm to press the button in the virtual environment. While this increases the immersive experience of the environment overall, it also heavily increases the response time range and variability. Thus, any effect that might be present on the response times could not be found with this study's experimental design. Note that while it would be possible to have participants answer using buttons on the controllers, they already had to get used to the controls for moving through the environment. Making additional buttons on the controllers relevant for the task might overall influence the perceived task difficulty and interfere with the participants' ability to navigate the virtual environment.

Also, no effect of the doorway condition or the change in room context could be demonstrated. The classic doorway phenomenon studies usually show that the correctness of responses to the memory probe is reduced after passing through a doorway, especially when comparing the "associated" to the "dissociated" objects [e.g., @Pettijohn_2015]. Such an effect might indeed also be present for the experimental design in the present study, but due to participants using very effective memory strategies, it might be hidden. Importantly, for the first and larger part of this experiment, participants consistently used the strategy of only remembering four objects, which is not a very high task difficulty or memory load. One could argue that the original experimental design for the doorway studies (picking up and carrying only one object at a time) leads to participants effectively only remembering two objects and thus the number of objects in the working memory is not a very relevant factor. However, in those experimental designs, the objects the participants interacted with were abstract shapes with different colours (e.g., a red pyramid and a blue cube), and the memory probe might either be one of those objects or a recombination (e.g., a red cube). Due to this design, there is a high probability of confusing the objects and colours, thus increasing the overall task difficulty - even if, in theory, only two objects are task-relevant. The present study however used differently coloured objects that could easily be identified or given a name (e.g., toy car, wrench, pink soap) and might thus have drastically lowered the overall task difficulty.

## Doorways and increased memory load reduce hit rate

While no effect on the overall percentage of correct responses could be found, the data was examined additionally using a signal detection based approach. For this, since 50% of the trials did contain a change in the object layout and 50% did not, it was possible to define hits (correctly detecting a change in the layout), misses (failing to detect a change in layout), false alarms (incorrectly responding the layout had changed if it was the same) and correct rejections (correctly identifying an unchanged layout as being the same). While this halved the number of trials included in this second analysis, it also revealed a small effect of the doorway condition on memory performance as measured by hit rate. In particular, participants gave 4.5% more correct responses if there was no doorway between the two rooms. This effect, while significant, is in practice extremely small (4.5% correspond to roughly 3 out of 64 trials). However, @McFadyen_2021 also examined the doorway effect using this definition of hits and misses and could show a doorway effect. Notably, their approach using signal detection theory might be relevant for a further examination for this study's memory task, since this way it would be possible to detect whether an overall reduction in memory performance (as measured by overall percentage correct responses) might be due to a reduction in hit rate or an increase in false alarm rate.

Additionally, in the second part of this study, participants were presented with a harder version of the memory task. They now had to remember a layout of seven objects, instead of only five. While no significant effects of doorway or context change could be found for these participants, there was a significant, but again very small difference in their confidence ratings. Previous research has not focused on evaluating subjective confidence or metacognition for the doorway phenomenon, but this might in fact be an option for further research. While response correctness measures actual memory performance, taking a look at metacognition might reveal the subjective perceived difficulty of the different experimental conditions. In fact, @Seel_2018 did not use confidence, but related measures to examine the difference of "remembering" (less confident) versus "knowing" (more confident) responses for a memory task in combination with the "doorway effect". They demonstrated that passing through a doorway reduces "remembering" (higher confidence) responses, while "knowing" (lower confidence) responses were unaffected. 

This, in addition with the previously mentioned work of @McFadyen_2021 and this study's failure to clearly demonstrate a "doorway effect" shows that this phenomenon might not be as strong and reliable as might be expected by the number of replications that mostly all use the same memory task.

@McFadyen_2021 could replicate a "doorway effect" only using an experimental condition with an increased memory load, and so the data collected for the present study have also been analysed using memory load as a measure. In particular, it was assumed that participants exhibiting an overall lower number of correct responses are either struggling with the task difficulty or do not use very effective strategies - both indicators that they might work under a higher working memory load. For this, only participants with less than 80% correct answers overall have been analysed, and indeed this was the condition where the biggest effect of the presence of a doorway on memory performance could be found - participants had a lower hit rate (61.5%) for the doorway condition as compared to the "no doorway" condition (70.9%). While this result is only exploratory, this might indeed indicate the presence of a ceiling effect, with participants performing too well in the task not being influenced by the doorway or environmental context conditions.

## Limitations and future research

While previous studies mainly examined the location updating effect using a non-immersive virtual environment (by presenting the experiment on a computer screen), here an immersive VR experience was created. While no effect of the room context on the memory performance could be demonstrated, this study still shows that virtual reality (VR) is a cheap and easy-to-use tool for examining cognitive processes, especially if the spatial layout and structure of an environment is of interest.

Regarding the underlying theory of event cognition, in particular the Event Horizon Model, the present study did not reveal any significant or unexpected information. Rather, the results should be taken as an indication that although there might be a consistent effect of doorways on "associated" objects being present in multiple event models (in comparison to "dissociated" objects), this effect fails to emerge once there is no explicit association of the objects in the working memory. The assumption for the current experimental design was that if the object layout is presented in two different rooms, it is also connected to two different event models, this might be questioned when looking at the results. One explanation might be that passively viewing the objects on the table, without interacting with them, might fail to "associate" them to the mental event models. A possibility to examine this would be to have participants "carry" the whole layout, for example by providing a box containing the different objects. However, considering the verbal feedback and the reported strategies of the participants, they might have done something conceptually similar already - they usually used a strategy of mentally repeating or visualising a list of objects while walking, which could use a similar mental representation as "carrying" those objects. Notably, previous experiments communicated the notion of "carrying" the associated object between the rooms only via visual information on a monitor screen, which might arguably constitute the same level of "association" as mentally repeating a list.

Although @Radvansky_2011 presented evidence that the level of immersion does not affect the doorway phenomenon, this could still be an area to explore in future studies. Since we are daily walking through real environments with doors and rich semantic and visual context changes, we might actually be too experienced in countering the effect resulting from crossing event boundaries. Using artificial environments presented on screens and using abstract, constructed objects as stimuli might result in a very unusual, "laboratory"-like experience that thus creates an artificial "doorway effect". Thus, by using highly immersive virtual environments and practically more relevant memory tasks and stimulus objects, future research could and indeed should consider the ecological validity of such experiments.

## Conclusion

While previous work has repeatedly and reliably replicated the "doorway effect", this study shows that this effect is not easily transferable onto an object layout memory task. Still, the results presented here should be considered as a first baseline for a new line of experiments on the doorway phenomenon using different experimental tasks. With immersive virtual reality, there exists a cheap and effective way of examining phenomena of cognitive processing in a more applied and realistic setting.




